### ISSUE TITLE
Update of CLI/REPL (Encoding on Windows) ?

### ISSUE THREAD

**Issue by jgranduel** [duckdb/duckdb#11246]
### What happens?

duckdb v0.10.0  on Windows Terminal 1.19, PowerShell-7.4

I have understood that DuckDB CLI/REPL is based on SQLite one. I don't know if it's still relevant with latest versions.

Since `SQLite-3.45` there is a very welcome amelioration of UTF-8 support in SQLite CLI/REPL (see [SQLite changes](https://www.sqlite.org/changes.html) for version 3.45).
There is not need for jungling with different encodins anymore (`.sys chcp 850` as a work around to get the boxed output).

Could you consider this improvement, please? as I still have to use 
`[Console]::OutputEncoding =[System.Text.Encoding]::GetEncoding(850)`  in my Terminal which is not friendly with other tools.
By default, I get in Terminal. Same issue with REPL.
```
������������������������������������������������Ŀ
�      name      �  column_a �      �  column_b  �
�     varchar      � varchar �      �  varchar   �
������������������������������������������������Ĵ
```
Thanks for considering this remark!

### To Reproduce

Example in REPL. File not queryable with changing the encoding

> duckdb.exe
v0.10.0 20b1486d11
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select "name" ->> '$.result' as name, "année" ->> '$.result' as year from 'a.json';
Error: Binder Error: Referenced column "année" not found in FROM clause!
Candidate bindings: "ann�e"
LINE 1: ...ect "name" ->> '$.result' as name, "année" ->> '$.result' as annee

D .sys chcp 850
Page de codes active : 850
D select "name" ->> '$.result' as name, "année" ->> '$.result' as annee
```
┌──────────────────┬──────────┐
│      name        │  annee   │
│     varchar      │ varchar  │
├──────────────────┼──────────┤
│ bob              │ 2024     │
...
```

### OS:

Windows-10

### DuckDB Version:

v0.10.0 20b1486d11

### DuckDB Client:

duckd CLI/REPL

### Full Name:

jgran

### Affiliation:

no affiliation

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for reporting! I have what I believe to be a fix up in https://github.com/duckdb/duckdb/pull/11324. Perhaps you could give it a shot locally and see if this fixes your issue?

**Comment by jgranduel** [comment]
Hi, 

Thank you very much for taking into account my report. The default behaviour for drawing a box is nicely solved.

There is still something that is annoying  in the UNICODE support. I don't know if I need to open a new issue or if this comment is the place to mention it.

```
> .\duckdb.exe
v0.10.2-dev181 8ce3df950c
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create table "éàùç" ("nom" text, "âge" integer);
D .schema
CREATE TABLE IF NOT EXISTS "├®├á├╣├º"(nom VARCHAR, "├óge" INTEGER);
D insert into "éàùç" values ('rené', 10), ('à@è😀', 15);
D select * from éàùç;
┌───────────┬───────┐
│    nom    │ ├óge  │
│  varchar  │ int32 │
├───────────┼───────┤
│ ren├®     │    10 │
│ ├á@├¿­ƒÿÇ │    15 │
└───────────┴───────┘
```

Compared to SQLite:

```
> sqlite3
SQLite version 3.45.0 2024-01-15 17:01:13 (UTF-16 console I/O)
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> create table "éàùç" ("nom" text, "âge" integer);


sqlite> insert into "éàùç" values ('rené', 10), ('à@è😀', 15);
sqlite> .mode box
sqlite> select * from éàùç;
┌──────┬─────┐
│ nom  │ âge │
├──────┼─────┤
│ rené │ 10  │
│ à@è😀 │ 15  │
└──────┴─────┘
sqlite>
```

I can't find the right encoding this time for correct display.

**Comment by Mytherin** [comment]
Thanks for reporting - I've pushed an additional fix in https://github.com/duckdb/duckdb/pull/11452 that should address the input issue as well.

**Comment by jgranduel** [comment]
Hi, 
Thanks! I tried the latest nightly build, but it might be a bit too early as the issue is not solved yet.

I will give it another try asap.

**Comment by Mytherin** [comment]
It has only been merged an hour ago - the nightlies should be available tonight

**Comment by jgranduel** [comment]
Hi, I've made a test with nightly build, following my previous example and I am very pleased to see it works nicely. Thanks A LOT  !
```
> .\duckdb.exe
v0.10.2-dev398 4da84ddf56
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create table "éàùç" ("nom" text, "âge" integer);
D .schema
CREATE TABLE IF NOT EXISTS "éàùç"(nom VARCHAR, "âge" INTEGER);
D insert into "éàùç" values ('rené', 10), ('à@è😀', 15);
D select * from éàùç;
┌─────────┬───────┐
│   nom   │  âge  │
│ varchar │ int32 │
├─────────┼───────┤
│ rené    │    10 │
│ à@è😀   │    15 │
└─────────┴───────┘
```

**Comment by jgranduel** [comment]
Hi, 

I tried latest release (`duckdb-v0.10.2 Bugfix Release`), and the nice layout expected is still not yet implemented as far as I've seen.
I then dowloaded laste nightly built (`v0.10.3-dev565 670cd34124`), and found that the previous display is back. Taking the same previous example:

```
> duckdb
v0.10.3-dev565 670cd34124
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D create table "éàùç" ("nom" text, "âge" integer);
D .schema
CREATE TABLE IF NOT EXISTS "éàùç"(nom VARCHAR, "âge" INTEGER);
D insert into "éàùç" values ('rené', 10), ('à@è😀', 15);
D select * from éàùç;
�������������������Ŀ
�    nom    � âge  �
�  varchar  � int32 �
�������������������Ĵ
� rené     �    10 �
� à@è😀 �    15 �
���������������������
```

Maybe I have forgottten something between my last trial?
Thx

**Comment by Mytherin** [comment]
See https://github.com/duckdb/duckdb/pull/11682, I've moved this behind an experimental flag (`.utf8`) since some users reported that my fix was causing problems for older versions of Windows. You can add `.utf8` to your `~/.duckdbrc` file to run this on start-up.

**Comment by jgranduel** [comment]
Sorry, 
I had just discovered the `.utf8` special command, and wanted to tell to not take my comment into account... You were too quick!
Thanks!

**Comment by daviewales** [comment]
I also needed to update my PowerShell `$PROFILE` to make this work.
So for me, the complete fix was:

**PowerShell $PROFILE**:

``` ps1
[Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8
```

**~/.duckdbrc**:

    .utf8
