### ISSUE TITLE
DuckDB crash on UNION ALL statement with > 350 SELECT's

### ISSUE THREAD

**Issue by rpbouman** [duckdb/duckdb#13096]
### What happens?

A statement like:

```
SELECT 1
UNION ALL
SELECT 2
UNION ALL
...
UNION ALL
SELECT 350
```

executes as expected. But add one more SELECT and DuckDB crashes. It doesn't give any error message, it just terminates and throws me back into the host. 

It does not appear to have anything todo with the size of the individual SELECTs, just with whehter there are more than 350 of them unioned together.

This does not happen on the GA release, but it happens on the nightly build (duckdb_cli-windows-amd64 /  v1.0.1-dev3170 18254ec5d9)

### To Reproduce

I'm attaching two files - 350_union_all.sql.txt which works, and 351_union_all.sql.txt, which crashes DuckDB
[350_union_all.sql.txt](https://github.com/user-attachments/files/16322345/350_union_all.sql.txt)
[351_union_all.sql.txt](https://github.com/user-attachments/files/16322346/351_union_all.sql.txt)

### OS:

windows 11 enterprise

### DuckDB Version:

v1.0.1-dev3170 18254ec5d9

### DuckDB Client:

CLI

### Full Name:

Roland Bouman

### Affiliation:

EPAM Systems BV Netherlands

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by carlopi** [comment]
Files appears to be the same, could you edit the issue? Thanks.

MacOS investigation:
* Up to 997 columns in the result it works.
* 998 columns throw a `Parser Error: Max expression depth limit of 1000 exceeded. Use "SET max_expression_depth TO x" to increase the maximum expression depth.` with default settings.
* With `SET max_expression_depth TO 10000` I managed to get to 5236 columns in the result, then I stop trying.

So MacOS looks to working as expected.

I have not tried on Windows, it will need to be investigated / solved there. Here it looks possible there are some OS-specific problems at play.

**Comment by rpbouman** [comment]
Ugh, I am sorry. Uploaded again.

[351_union_all.sql.txt](https://github.com/user-attachments/files/16323692/351_union_all.sql.txt)
[350_union_all.sql.txt](https://github.com/user-attachments/files/16323693/350_union_all.sql.txt)

**Comment by carlopi** [comment]
Could you possibly try with the new nightly version?
It sounds like something that might have been addressed by https://github.com/duckdb/duckdb/pull/13280

**Comment by rpbouman** [comment]
Hi @carlopi ! I just downloaded v1.0.1-dev3762 566eb853c8 cli and interestingly enough, it now crashes on 350 and 351 rows (both earlier attached files) 

By some weird coincidence, it doesn't at 349. Attaching that:

[349_union_all.sql.txt](https://github.com/user-attachments/files/16478625/349_union_all.sql.txt)

**Comment by rpbouman** [comment]
Today, I downloaded 1.1.3 GA (v1.1.3 19864453f7) and I can still reproduce this problem but now with 331 union all items (attached)
[331_union_all.sql.txt](https://github.com/user-attachments/files/17621347/331_union_all.sql.txt)

**Comment by rpbouman** [comment]
I just downloaded and checked with v1.2.2 7c039464e4.
I can still reproduce the issue on windows 11 x64 using the prior 331_union_all.sql script.

**Comment by rpbouman** [comment]
Can't reproduce anymore in 1.5.2
