### ISSUE TITLE
JOIN fails on string columns in 1.3.0 but works in 1.2.2

### ISSUE THREAD

**Issue by fjossandon** [duckdb/duckdb#17891]
### What happens?

I have multiple SQL database copies, and I'm using DuckDB to pull their data and compare if their IDs are different. The issue happened when comparing 2 equivalent tables that store unique large public DNA sequences, where I have to join both tables by the sequence to get their ID equivalencies. I got some weird results, and it took me a while to narrow down the cause. I noticed that a couple of rows (that I knew were identical in both) were missing when running my Python program. This inconsistency was not happening in my local environment, which used DuckDB 1.2.2, but appeared on a different computer with DuckDB 1.3.0 installed.

The table contains millions of sequences, so I tried to trim it down as much as possible to create a test case (only leaving identical data in both), since the bug disappears if I only leave the rows originally affected and delete everything else. So it looks like an edge case that is content-dependent. During the trimming process, I removed rows and repeated a query until the bug did not appear anymore. During that process, I saw fluctuations in the bug, between 1 and 4 rows failing to join.
```
id: 878418, matches_ids: 888328, matches_keys: 888326, diff: 2
id: 868418, matches_ids: 878328, matches_keys: 878327, diff: 1
id: 858418, matches_ids: 868328, matches_keys: 868327, diff: 1
id: 848418, matches_ids: 858328, matches_keys: 858324, diff: 4
id: 838418, matches_ids: 848328, matches_keys: 848324, diff: 4
```

The most trimmed-down version still contains 240K rows, so I'm sharing it from my  Google Drive until it can be reproduced and debugged:
https://drive.google.com/file/d/1mQQSI-PiD_tTTuMy9b647p9cJ0fYOLi-/view?usp=sharing

### To Reproduce

Download the DuckDB file from the Drive link. It only contains 2 tables: `seqs_table_a` and `seqs_table_b`. Both tables have 2 columns (id & key), and they have the same data. Joining the tables by the "id" or "key" columns should return the exact same results.

Extra requirements:
```
numpy           1.26.4
pandas          2.2.3
```
This is a Python script to reproduce it, using only DuckDB queries.
```python
import duckdb

duckdb_conn = duckdb.connect("duckdb.db")

matches_ids = (
    duckdb_conn.sql(
        """
    SELECT COUNT(o.id) AS matches_ids
    FROM "seqs_table_a" AS o
    INNER JOIN "seqs_table_b" AS d
      ON d.id = o.id
    ;
    """,
    )
    .to_df()["matches_ids"]
    .to_list()[0]
)

matches_ids_keys = (
    duckdb_conn.sql(
        """
    SELECT COUNT(o.id) AS matches_ids
    FROM "seqs_table_a" AS o
    INNER JOIN "seqs_table_b" AS d
      ON d.id = o.id
    WHERE d.key = o.key
    ;
    """,
    )
    .to_df()["matches_ids"]
    .to_list()[0]
)

if matches_ids != matches_ids_keys:
    duckdb_conn.close()
    msg = f"Keys mismatches! {matches_ids} vs {matches_ids_keys}"
    raise ValueError(msg)

matches_keys = (
    duckdb_conn.sql(
        """
    SELECT COUNT(o.id) AS matches_keys
    FROM "seqs_table_a" AS o
    INNER JOIN "seqs_table_b" AS d
      ON d.key = o.key
    ;
    """,
    )
    .to_df()["matches_keys"]
    .to_list()[0]
)

mismatches_keys = (
    duckdb_conn.sql(
        """
    WITH orig AS (
        SELECT o.id
        FROM "seqs_table_a" AS o
        INNER JOIN "seqs_table_b" AS d
          ON d.key = o.key
    ),
    dest AS (
        SELECT o.id
        FROM "seqs_table_b" AS o
        INNER JOIN "seqs_table_a" AS d
          ON d.key = o.key
    ),
    orig_mm AS (
        SELECT a.id
        FROM "seqs_table_a" AS a
        LEFT JOIN orig AS o
          ON o.id = a.id
        WHERE o.id IS NULL
    ),
    dest_mm AS (
        SELECT b.id
        FROM "seqs_table_b" AS b
        LEFT JOIN dest AS d
          ON d.id = b.id
        WHERE d.id IS NULL
    )
    SELECT CONCAT_WS(
             ' - ',
             'orig',
             o.id
           ) AS mismatch
    FROM orig_mm AS o
    UNION
    SELECT CONCAT_WS(
             ' - ',
             'dest',
             d.id
           ) AS mismatch
    FROM dest_mm AS d
    ;
    """,
    )
    .to_df()["mismatch"]
    .to_list()
)

print(
    f"matches_ids: {matches_ids}, "
    f"matches_keys: {matches_keys}, "
    f"diff: {matches_ids - matches_keys}, "
    f"mismatches_keys: {sorted(mismatches_keys)}",
)

```
The `matches_ids` provide the Control result (joining by id), while `matches_keys` are the different results when joining by the key string. The queries are a little convoluted because I wanted to see if the joining order affected it, and while trimming, sometimes gave a different result.

This is the expected output with DuckDB 1.2.2:
```
matches_ids: 240001, matches_keys: 240001, diff: 0, mismatches_keys: []
```
And this is the result with DuckDB 1.3.0:
```
matches_ids: 240001, matches_keys: 240000, diff: 1, mismatches_keys: ['dest - 177599', 'orig - 177599']
```

### OS:

Ubuntu 24.04.2 LTS

### DuckDB Version:

1.3.0

### DuckDB Client:

Python 3.12.3

### Full Name:

Francisco Ossandon

### Affiliation:

Biome Makers

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

**Comment by szarnyasg** [comment]
@fjossandon, thanks for the reproducer. I could reproduce the issue on macOS.

**Comment by szarnyasg** [comment]
@fjossandon the team tells me that this has been fixed on the `v1.3-ossivalis` branch, which will be released next week as part of v1.3.1. Stay tuned.

**Comment by fjossandon** [comment]
@szarnyasg excellent! I will be waiting for that release. 👍

**Comment by fjossandon** [comment]
Hello @szarnyasg, just wanted to inform you that I installed v1.3.1, but the bug is still present.

**Comment by ctberthiaume** [comment]
I also want to report that I have independently encountered this bug with my own data when using v1.3.0, so it may be fairly common above a certain data size (or I'm just unlucky). At the moment I'm using v1.2.2 to get reliable string joins. I just ran the repro code provided by @fjossandon to test v1.3.2 and it looks like the bug is still present.

**Comment by fjossandon** [comment]
Hello @szarnyasg!
Like @ctberthiaume did, I also tested 1.3.2, and the bug is still present, so it seems the hotfixes in 1.3.1 and 1.3.2 were not related to this after all.
Do you know if anyone is looking at it, or if there is any progress on it?
Best regards,

**Comment by lnkuiper** [comment]
Closed via https://github.com/duckdb/duckdb/pull/18374

Will be released in v1.4.0

**Comment by fjossandon** [comment]
I just tested DuckDB version 1.4.0 using both the trimmed-down tables I shared here (with 240K sequences) and my original full tables with ~2 million sequences, and they passed without errors:
```
$ python3 duckdb_issue.py 
matches_ids: 240001, matches_keys: 240001, diff: 0, mismatches_keys: []

$ python3 duckdb_issue.py 
matches_ids: 1908418, matches_keys: 1908418, diff: 0, mismatches_keys: []
```
The bug is fixed, so I will remove the DuckDB file I was sharing as a test case from my Drive.

Thanks a lot!
