### ISSUE TITLE
Deleting with DELETE USING causes a segmentation fault

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb#1834]
**What does happen?**
I am performing deletes with the `DELETE ... USING ...` (#1659) command. In some cases, it returns with a segmentation fault.

I have also seen a few `Conflict on tuple deletion!` but the root cause of the two seems to be the same (sometimes, running the same script multiple times returns either a segfault or a conflict).

**What should happen?**
The system should perform the delete operation on the tuples matching the condition.

**To Reproduce**
1. Grab the archive containing the data and the script  from https://surfdrive.surf.nl/files/index.php/s/VA92agRErNV2EJl
2. Run the SQL script:
   ```bash
   cat delete-segfault-mwe.sql | sed "s#PATHVAR#`pwd`/data#" | duckdb
   ```

    It returns a `Segmentation fault (core dumped)`

**Environment (please complete the following information):**
 - OS: Fedora 34
 - DuckDB Version: 0.2.6, master (979f14ed48b865e0f775b2898640757b6302f4e7)

The content of the SQL script is the following:
```sql
CREATE TABLE Person_likes_Comment (creationDate timestamp without time zone not null, id bigint not null, likes_Comment bigint not null);
CREATE TABLE Person_Delete_candidates (deletionDate timestamp without time zone not null, id bigint);

COPY Person_likes_Comment FROM 'PATHVAR/Person_likes_Comment.csv' (DELIMITER '|', TIMESTAMPFORMAT '%Y-%m-%dT%H:%M:%S.%g+00:00');
COPY Person_Delete_candidates FROM 'PATHVAR/Person_Delete_candidates.csv' (DELIMITER '|', HEADER, TIMESTAMPFORMAT '%Y-%m-%dT%H:%M:%S.%g+00:00');

DELETE FROM Person_likes_Comment USING Person_Delete_candidates WHERE Person_Delete_candidates.id = Person_likes_Comment.id;
```

The following query returns the tuples that should be deleted from the `Person_likes_Comment` (showing that there are no duplicates):
```sql
SELECT Person_likes_comment.* FROM Person_likes_Comment, Person_Delete_candidates WHERE Person_Delete_candidates.id = Person_likes_Comment.id;
```

**Comment by PedroTadim** [comment]
I got the "Conflict on tuple deletion!" error too. It was because a row got more than one match in the join. A different check should be needed, such as a join where a row cannot have more than one match. In MonetDB it's a single join.

**Comment by szarnyasg** [comment]
Thanks for looking into it.

> It was because a row got more than one match in the join.

I think `USING` should support that based on the example in https://www.postgresql.org/docs/13/sql-delete.html:

```sql
DELETE FROM films USING producers
  WHERE producer_id = producers.id AND producers.name = 'foo';
```

Interestingly, if I turn the join into a selection, it works:

```sql
DELETE FROM Person_likes_Comment USING Person_Delete_candidates WHERE Person_likes_Comment.id = 26388279076874;
```

**Comment by szarnyasg** [comment]
I ran it in `gdb` and there it reliably produces the `TransactionContext Error: Conflict on tuple deletion!` message.
```
$ gdb --args ./build/reldebug/test/unittest test/delete-using-segfault.test
```
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[0/1] (0%): test/delete-using-segfault.test                                     
================================================================================
Query unexpectedly failed! (test/delete-using-segfault.test:15)!
================================================================================
SQL Query
DELETE FROM Person_likes_Comment USING Person_Delete_candidates WHERE Person_Delete_candidates.id = Person_likes_Comment.id;
================================================================================
TransactionContext Error: Conflict on tuple deletion!
```

**Comment by Mytherin** [comment]
Thanks for the detailed report! I have pushed a fix in #1837. Could you see if that resolves the problem for you?

**Comment by szarnyasg** [comment]
@Mytherin thanks for the quick fix. The original problem was indeed fixed and there are no more segfaults. However, I still get `TransactionContext Error: Conflict on tuple deletion!` errors on some deletions. Here is another MWE:

https://surfdrive.surf.nl/files/index.php/s/jqCfAuZJyfJdsgK

```
$ duckdb --version
v0.2.7-dev626 f3d5be47fc

$ cat delete-segfault-mwe2.sql | sed "s#PATHVAR#`pwd`/data#" | duckdb
Error: near line 9: TransactionContext Error: Conflict on tuple deletion!
```

This `DELETE` query does not have any joins, the `USING` cause only refers to table `Forum_Delete_candidates`.

```sql
CREATE TABLE Forum (creationDate timestamp without time zone not null, id bigint not null, title varchar(256) not null, hasModerator_Person bigint not null);

CREATE TABLE Forum_Delete_candidates (deletionDate timestamp without time zone not null, id bigint);

COPY Forum FROM 'PATHVAR/Forum.csv' (DELIMITER '|', HEADER, TIMESTAMPFORMAT '%Y-%m-%dT%H:%M:%S.%g+00:00');

COPY Forum_Delete_candidates FROM 'PATHVAR/Forum_Delete_candidates.csv' (DELIMITER '|', HEADER, TIMESTAMPFORMAT '%Y-%m-%dT%H:%M:%S.%g+00:00');

DELETE FROM Forum USING Forum_Delete_candidates;
```

**Comment by Mytherin** [comment]
Thanks for the new report! I managed to reproduce this behavior with a smaller example. Could you check if #1838 solves the problem for you?

**Comment by szarnyasg** [comment]
It works like a charm on my (fairly convoluted) [deletion script](https://github.com/ldbc/ldbc_snb_data_converter/blob/927817baf657a4d1b226ffd212486e416abb764e/workflow-sql-datagen/sql/snb-deletes.sql). Thanks for the fix!
