### ISSUE TITLE
Update Performance - executemany execution time is unexpectedly slow

### ISSUE THREAD

**Issue by Admolly** [duckdb/duckdb#2458]
I have been testing some UPDATE queries and the performance is slow.  For reference I am running version 0.2.9 on Windows 10.  

The query itself is pretty simple:

```
UPDATE main.users 
SET updated_at = ?
WHERE id = ? AND database = ?
```

I wrap the query in a single call to `con.executemany` and supply that values for updated_at, id, and database as a list of lists (id and database are composite keys for the table main.users).

The time to execute takes much longer than what I expected (longer than it takes to populate the entire table) given the relatively small payload.  Here is a summary of the performance:

|   rows_updated|   table_size |   time (s) |
|----------------:|-------------:|-----------:|
|          1,937 |      60,730 |       3.94 |
|          1,956 |   23,930,564 |     588.5  |
|          2,895 |     942,484 |      44.4  |
|          2,935 |   23,930,564 |     863.0  |
|          4,608 |    1,052,501 |      94.7  |
|          5,715 |    1,752,080 |     138.8  |
|          8,091 |    2,151,138 |     235.2  |
|         10,356 |    5,349,655 |     651.3  |

A bit surprised how much the execution time seems to depend on table size rather than number of rows updated. Was hoping someone can maybe give me some pointers on how to improve performance in this particular case and an explanation why performance is suffering so much.

**Comment by Admolly** [comment]
OK, so if I understand correctly you are suggesting I do something like:

```
UPDATE schema.table
SET col = REPLACE(col, pattern1, pattern2)
WHERE col LIKE pattern1
```

This isn't exactly what I'm looking for, but I suppose I could make it work.  Do you think that this issue could be resolved within the next few releases?

**Comment by Admolly** [comment]
Ah OK.  Thank you for the clarification.

**Comment by Mytherin** [comment]
Perhaps try reducing the memory limit (e.g. `PRAGMA memory_limit='XGB'`). Indexes are not buffer managed yet and hence can cause excess memory usage past the memory limit which can cause these issues.

**Comment by Mytherin** [comment]
As mentioned before indexes are not buffer managed yet and do not count towards the memory limit, if you are using indexes then it is expected that the memory limit is exceeded in this manner currently.

**Comment by Admolly** [comment]
Sorry to leave this issue hanging for so long.  After tinkering around it appears that the crashes were unrelated to the memory usage by the indexes and were instead related to a bug in the PyRelation object that was resolved by upgrading from v0.2.9 to v0.3.0.  I have re-run the update queries without using `executemany` and the update times no longer depend on the size of the table being update.  See the table below for some statistics:

|   rows_updated|   table_size |   time (s) |
|----------------:|-------------:|-----------:|
|          3,143 |      24,324,315 |       7.04 |
|          1,007 |   23,930,564 |     1.72  |
|          782 |     3,545,319 |      1.41  |

Perhaps it's not a bad idea to keep the issue open as long as the issues with `executemany` persist.  I will re-name the title to something a bit more descriptive.

**Comment by andreamoro** [comment]
## Still an issue in v1.4.2 — 8+ minutes vs 0.05s for 76K rows

I ran into this while building a personal NLP pipeline project. The pipeline persists term frequency data to DuckDB — 382 documents x ~200 terms each = ~76K rows. Using `executemany`, persistence took **over 8 minutes**. Switching to `read_csv()` brought it down to **under a second**.

Spent hours debugging, suspecting batch sizes, DELETE operations, table bloat, or Python loop overhead — none of which were the actual problem.

### Environment

- DuckDB: **1.4.2** (Python client)
- Python: **3.13.9**
- OS: **Ubuntu Linux 6.17.0-8-generic, x86_64**

### Reproducible benchmark

```python
import time, os, csv, tempfile, duckdb

# Generate 76,400 rows (382 docs x 200 terms)
rows = [
    (f'doc_{i}', f'term_{j}', j + 1, (j + 1) / 500.0)
    for i in range(382) for j in range(200)
]
cols = ['document_id', 'term', 'raw_count', 'tf_score']
print(f"Rows: {len(rows)}")

db = '/tmp/test_executemany.duckdb'
schema = 'CREATE TABLE test (document_id TEXT, term TEXT, raw_count INTEGER, tf_score DOUBLE)'

# --- Method 1: executemany ---
if os.path.exists(db): os.remove(db)
conn = duckdb.connect(db)
conn.execute(schema)
t0 = time.perf_counter()
conn.executemany('INSERT INTO test VALUES (?, ?, ?, ?)', rows)
print(f"executemany:      {time.perf_counter() - t0:.2f}s")
conn.close()

# --- Method 2: executemany in 382 batches of 200 ---
if os.path.exists(db): os.remove(db)
conn = duckdb.connect(db)
conn.execute(schema)
t0 = time.perf_counter()
for i in range(382):
    batch = rows[i * 200:(i + 1) * 200]
    conn.executemany('INSERT INTO test VALUES (?, ?, ?, ?)', batch)
print(f"executemany x382: {time.perf_counter() - t0:.2f}s")
conn.close()

# --- Method 3: CSV temp file + read_csv ---
if os.path.exists(db): os.remove(db)
conn = duckdb.connect(db)
conn.execute(schema)
t0 = time.perf_counter()
with tempfile.NamedTemporaryFile(mode='w', suffix='.csv', delete=False, newline='') as f:
    csv_path = f.name
    writer = csv.writer(f)
    writer.writerow(cols)
    writer.writerows(rows)
conn.execute(f"INSERT INTO test SELECT * FROM read_csv('{csv_path}', header=true)")
os.remove(csv_path)
print(f"CSV + read_csv:   {time.perf_counter() - t0:.2f}s")
conn.close()

os.remove(db)
```

### Results

| Method | Time | Factor |
|---|---|---|
| `executemany` (single call, 76K rows) | **16.08s** | 1x |
| `executemany` (382 calls x 200 rows) | **16.90s** | ~1x |
| CSV temp file + `read_csv()` | **0.05s** | **~320x faster** |

Batching doesn't help — `executemany` is equally slow whether called once with 76K rows or 382 times with 200 rows. The overhead is clearly per-row, not per-call.

### Real-world context

In my pipeline, the full persistence cycle (serialize + DELETE existing + `executemany` INSERT) for 382 documents took **8 minutes 37 seconds** wall clock. After switching to CSV-based insertion, the same operation completes in **~3 seconds** including serialization, DELETE, CSV write, and `read_csv` INSERT.

### Workaround

Write data to a temp CSV and use `read_csv()`. It uses DuckDB's native vectorized scanner instead of the row-by-row Python API path. No extra dependencies — just stdlib `csv` and `tempfile`.
