### ISSUE TITLE
pip install duckdb requires Microsoft Visual C++ 14.0

### ISSUE THREAD

**Issue by pppdddppp** [duckdb/duckdb#3461]
#### What happens?
pip install of duckdb v0.3.3 fails on Windows with following error:

      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

pip installing latest master branch works fine ( `pip install duckdb --upgrade --pre`)

#### To Reproduce
pip install duckdb==0.3.3

#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version: 0.3.3
 - DuckDB Client: Python

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Alex-Monahan** [comment]
Hi!

This is actually a known issue. We did not upload all of the pre-compiled binaries for the 0.3.3 release that we typically do (due to a CI/CD kssue). We will be posting a bug fix release before long, and using master in the meantime (or using Python 3.10!) should work.

Thanks for reporting the bug!

**Comment by Mytherin** [comment]
Should be fixed with 0.3.4

**Comment by aalexandersson** [comment]
The error is back on Python 3.11.  Please advise.
**To reproduce:**
```
pip install duckdb==0.3.4
```

**Environment (please complete the following information):**
OS: Windows 10
DuckDB Version: 0.3.4
DuckDB Client: Python 3.11.0

**Comment by Alex-Monahan** [comment]
> The error is back on Python 3.11. Please advise. **To reproduce:**
> 
> ```
> pip install duckdb==0.3.4
> ```
> 
> **Environment (please complete the following information):** OS: Windows 10 DuckDB Version: 0.3.4 DuckDB Client: Python 3.11.0

Hello! Python 3.11 did not exist when DuckDB 0.3.4 was released, so we did not upload a precompiled binary for it. Is there anything preventing you from upgrading to 0.6.0?

**Comment by aalexandersson** [comment]
Thank you, very helpful. Yes, `splink==3.0.0dev6` for probabilistic record linkage is incompatible with `duckdb==0.6.0`. That is,

```
pip3 install -r requirements.txt
```
results in this error:

```
ERROR: Cannot install -r requirements.txt (line 42) and duckdb==0.6.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested duckdb==0.6.0
    splink 3.0.0.dev6 depends on duckdb<0.4.0 and >=0.3.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```
Is there a precompiled version of duckdb<0.4.0 and >=0.3.5 for Python 3.11?   I will also try to loosen the `splink` requirements.

**Comment by aalexandersson** [comment]
With the latest version `splink==3.4.2`, the result is a similar dependency conflict with `duckdb`:

```
The user requested duckdb==0.6.0
    splink 3.4.2 depends on duckdb<0.6.0 and >=0.5.0
```
With `duckdb==0.5.1` I get the original error [pip install duckdb requires Microsoft Visual C++ 14.0](https://github.com/duckdb/duckdb/issues/3461#top). I will try to see if splink 3.4.2 maybe could allow (precompiled) duckdb 0.6.0.

**Comment by liquidcarbon** [comment]
Same issue as @Prussian1870 on Win11 and py3.12
The installer for MSFT C++ build tools suggested in the end of the error message requires admin rights.

**Comment by Flurven** [comment]
Same issue.
