### ISSUE TITLE
read_json_auto: duckdb.IOException: IO Error: Cannot open file "xxx": Too many open files

### ISSUE THREAD

**Issue by timon-schmelzer-gcx** [duckdb/duckdb#6249]
### What happens?

When reading about 1000 json files, I recieve the following error:

    read_json_auto: duckdb.IOException: IO Error: Cannot open file "xxx": Too many open files

The same works when reading 1000 csv files (see example below).

### To Reproduce

```python
import shutil
from pathlib import Path

import duckdb
import pandas as pd

if __name__ == "__main__":
    mode = "json"  # "json", "csv"

    data_dir = Path("data")
    if data_dir.exists():
        shutil.rmtree(data_dir)
    data_dir.mkdir(exist_ok=True)

    for i in range(1000):
        df = pd.DataFrame({"a": [1, 2, 3]})

        if mode == "json":
            df.to_json(data_dir / f"file_{i}.json", lines=True, orient="records")
        else:
            df.to_csv(data_dir / f"file_{i}.csv")

    data = duckdb.sql(f"SELECT COUNT(*) FROM read_{mode}_auto('{data_dir}/*.{mode}');")

    print(data.fetchone())
```
When setting `mode="csv"`, the code works as expected.

### OS:

macOS

### DuckDB Version:

0.7.0

### DuckDB Client:

Python

### Full Name:

Timon Schmelzer

### Affiliation:

grandcentrix

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
Thanks for the bug report! We weren't properly closing JSON files. I have pushed a fix in my fork, will send a PR soon.

**Comment by timon-schmelzer-gcx** [comment]
Hey! I installed the newest version of DuckDB (0.7.1) and still receive the same error using the code snipped above. Is there anything I can do?
