### ISSUE TITLE
DuckDB hang on `DELETE`

### ISSUE THREAD

**Issue by DerZc** [duckdb/duckdb#7610]
### What happens?

DuckDB hang on the following program:
```
CREATE TABLE t0(c0 VARCHAR);

INSERT INTO t0(c0) VALUES ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a'), ('a');

UPDATE t0 SET c0=('1969-12-15 04:49:07');

CREATE INDEX i4 ON t0(c0);
DELETE FROM t0;
```

### To Reproduce

I can reproduce this with the latest commit version https://github.com/duckdb/duckdb/commit/85989198104c893f302e2fff6fae6bba65156af8

### OS:

ubuntu 22.04

### DuckDB Version:

https://github.com/duckdb/duckdb/commit/85989198104c893f302e2fff6fae6bba65156af8

### DuckDB Client:

CLI

### Full Name:

Chi Zhang

### Affiliation:

Nanjing University, National University of Singapore

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

This looks very similar to #7530 which was already fixed - and I cannot seem to reproduce it on the latest master. Are there specific configuration flags you are using during compilation perhaps?

**Comment by DerZc** [comment]
Hi @Mytherin I just tried on another machine and can still reproduce. I just clone the Github repo and make it with `make all -j`, then run `./duckdb/build/release/duckdb < test.sql`, I can reproduce this on Ubuntu 22.04.

**Comment by taniabogatsch** [comment]
I can reproduce this one, I can have a look. The original reproducible example succeeds on my machine.
```
CREATE TABLE t0(c0 TIMESTAMP);
CREATE TABLE t67(c0 VARCHAR);
INSERT INTO t0(c0) VALUES (DEFAULT);
CREATE VIEW v0(c0) AS SELECT t67.rowid FROM t67 ORDER BY ((DATE '1969-12-13') IN (t67.c0, ((((t67.rowid))) IS NULL), (false))) DESC LIMIT (950582599);
SELECT (t0.c0) AS c0, (t0.rowid) AS c1 FROM v0 NATURAL FULL JOIN t0 WHERE (TIMESTAMP '1970-01-22 15:51:19');
```
