### ISSUE TITLE
Multiple Python threads causing a hang

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#8098]
### What happens?

If I run a slightly simplified version of the multiple python threads example from the docs, it hangs indefinitely. 

### To Reproduce

```python
import duckdb
from threading import Thread, current_thread
import random
import datetime

print(datetime.datetime.now())

# duckdb_con = duckdb.connect('md:') 
duckdb_con = duckdb.connect() 
# duckdb_con.execute('INSTALL httpfs;')
# duckdb_con.execute('LOAD httpfs;')
       

def read_from_thread(duckdb_con):
    # Create a DuckDB connection specifically for this thread
    local_con = duckdb_con.cursor()
    # Query the current row count
    thread_name = str(current_thread().name)
    results = local_con.execute("""
        select 42
    """).df()
    print(results.head(1))

read_thread_count = 2
threads = []

# Create multiple reader threads (in the same process) 
# Pass in the same connection as an argument


for j in range(read_thread_count):
    threads.append(Thread(target=read_from_thread,
                            args=(duckdb_con,),
                            name='read_thread_'+str(j)))

# Shuffle the threads to simulate a mix of readers and writers
random.seed(6) # Set the seed to ensure consistent results when testing
random.shuffle(threads)

# Kick off all threads in parallel
for thread in threads:
    thread.start()

# Ensure all threads complete before printing final results
for thread in threads:
    thread.join()

print(datetime.datetime.now())

```

Setting the thread count to 1 will succeed, but 2 or greater will hang indefinitely.

### OS:

MacOS

### DuckDB Version:

0.8.1 and latest master

### DuckDB Client:

Python

### Full Name:

Alex Monahan

### Affiliation:

MotherDuck / DuckDB Foundation

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
I have also validated that creating a new cursor in the main thread and then passing it in as an argument also fails in the same way. I also tested both in memory and persistent databases.

**Comment by Alex-Monahan** [comment]
It also fails if I create an entirely new connection to the same physical database within each thread.

**Comment by Tishj** [comment]
adding `import numpy.core.multiarray` seems to fix the issue
This seems related to an issue I also encountered and fixed in #7751

`import numpy.core.multiarray` has to be performed from the main thread for some reason
So in the dataframe result collection we now always import this module to make sure it's available in the worker threads

**Comment by Alex-Monahan** [comment]
We ran into this again during some fuzzing on the MotherDuck side. The issue is still present in the latest master (0.8.2-dev3092). 

You are correct that importing `import numpy.core.multiarray` fixes the issue. 

Other fixes include using `.fetchall()` or `.arrow()` instead of `.df()`, so the issue is squarely in numpy/pandas-land.
