### ISSUE TITLE
Error when attaching a remote db with FTS

### ISSUE THREAD

**Issue by AndreaFrancis** [duckdb/duckdb#8141]
### What happens?

When trying to attach a db that has a fts index, it fails to fetch data using match_bm25 macro.
Error:

```
 line 22, in <module>
    result = con.execute(
duckdb.BinderException: Binder Error: Catalog "index" does not exist!

```

### To Reproduce

```
import duckdb

con = duckdb.connect()

INSTALL_EXTENSION_COMMAND = "INSTALL '{extension}';"
LOAD_EXTENSION_COMMAND = "LOAD '{extension}';"

con.execute(INSTALL_EXTENSION_COMMAND.format(extension="httpfs"))
con.execute(LOAD_EXTENSION_COMMAND.format(extension="httpfs"))
con.execute(INSTALL_EXTENSION_COMMAND.format(extension="fts"))
con.execute(LOAD_EXTENSION_COMMAND.format(extension="fts"))

INDEX_URL = "https://huggingface.co/datasets/asoria/copy_e_glue/resolve/refs%2Fconvert%2Fparquet/default/test/index.duckdb"
ATTACH_COMMAND = f"ATTACH '{INDEX_URL}' as db;"

con.execute(ATTACH_COMMAND)
con.execute("use db;")

query = "denominator"
result = con.execute(
    "SELECT * FROM data WHERE fts_main_data.match_bm25(__hf_index_id, ?) IS NOT NULL;",
    [query],
)

rows = result.df()
print(f"{rows=}")
con.close()
```

### OS:

Ubuntu 22.04.2 LTS x86_64

### DuckDB Version:

0.8.2.dev161

### DuckDB Client:

Python 0.8.2.dev161

### Full Name:

Andrea Soria

### Affiliation:

Hugging Face

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
This looks similar to https://github.com/duckdb/duckdb/issues/7384

**Comment by Mytherin** [comment]
Should be fixed now

**Comment by AndreaFrancis** [comment]
I tried the fix with the master version (0.8.2.dev1212) but it is still failing:

```
import duckdb

INSTALL_EXTENSION_COMMAND = "INSTALL '{extension}';"
LOAD_EXTENSION_COMMAND = "LOAD '{extension}';"
INDEX_FILENAME = "index.duckdb"
CREATE_SEQUENCE_COMMAND = "CREATE OR REPLACE SEQUENCE serial START 1;"
CREATE_INDEX_COMMAND = "PRAGMA create_fts_index('data', '__index', '*', overwrite=1);"
CREATE_TABLE_COMMAND = "CREATE OR REPLACE TABLE data AS SELECT nextval('serial') AS __index, * FROM"

con = duckdb.connect(INDEX_FILENAME)

con.execute(INSTALL_EXTENSION_COMMAND.format(extension="httpfs"))
con.execute(LOAD_EXTENSION_COMMAND.format(extension="httpfs"))
con.execute(INSTALL_EXTENSION_COMMAND.format(extension="fts"))
con.execute(LOAD_EXTENSION_COMMAND.format(extension="fts"))

con.sql(CREATE_SEQUENCE_COMMAND)

parquet_urls = ["https://huggingface.co/datasets/asoria/copy_e_glue/resolve/refs%2Fconvert%2Fparquet/default/copy_e_glue-test.parquet"]
create_command_sql = f"{CREATE_TABLE_COMMAND} read_parquet({parquet_urls});"
con.sql(create_command_sql)

create_index_sql = CREATE_INDEX_COMMAND
con.sql(create_index_sql)
con.close()

mem_con = duckdb.connect()
mem_con.execute(INSTALL_EXTENSION_COMMAND.format(extension="httpfs"))
mem_con.execute(LOAD_EXTENSION_COMMAND.format(extension="httpfs"))
mem_con.execute(INSTALL_EXTENSION_COMMAND.format(extension="fts"))
mem_con.execute(LOAD_EXTENSION_COMMAND.format(extension="fts"))

ATTACH_COMMAND = f"ATTACH '{INDEX_FILENAME}' as db;"

mem_con.execute(ATTACH_COMMAND)
mem_con.execute("use db;")
record_count = mem_con.sql("SELECT COUNT(*) FROM data;").fetchall()
print(f"{record_count=}")  # OK -It returns the correct number of rows

query = "denominator"
result = mem_con.execute(
    "SELECT * FROM data WHERE fts_main_data.match_bm25(__index, ?) IS NOT NULL;",
    [query],
)  # FAIL - Binder Error: Catalog "index" does not exist!

rows = result.df()
print(f"{rows=}")
mem_con.close()

```

As you can see, in the first part I generate a db file with a fts index and then I try to load it for search but the problem is the same:


```

    result = mem_con.execute(
duckdb.BinderException: Binder Error: Catalog "index" does not exist!
```

Am I doing something wrong?

**Comment by Mytherin** [comment]
@lnkuiper could you have another look when you have time?
