### ISSUE TITLE
Regression in Python read_csv v0.9.0

### ISSUE THREAD

**Issue by jamalsa** [duckdb/duckdb#9124]
### What happens?

On version 0.8.1 Python client can read this csv file correctly:
https://www.kaggle.com/datasets/stefanoleone992/fifa-23-complete-player-dataset?select=male_players.csv

On version 0.9.0 it failed with error `Invalid Input Error: Error in file "male_players.csv": CSV options could not be auto-detected. Consider setting parser options manually.`

### To Reproduce

Python code:
```python
import duckdb
import time

filename = "male_players.csv"
print(f"Read csv at {filename}")
start = time.time()
try:
    data = duckdb.read_csv(filename)
except duckdb.InvalidInputException as e:
    print(e)
end = time.time()
duration = end - start
print(f"Read done with duration {duration}s")
```

Version 0.8.1 output:
```bash
Read csv at male_players.csv
Read done with duration 0.6689996719360352s
```

Version 0.9.0 output:
```bash
Read csv at male_players_23.csv
Invalid Input Error: Error in file "male_players_23.csv": CSV options could not be auto-detected. Consider setting parser options manually.
Read done with duration 338.90412878990173s
```

Also the read time is much much slower (0.66s vs 338.9 s) but maybe because DuckDB cannot parse the csv.

### OS:

Windows 11 x64

### DuckDB Version:

0.9.0

### DuckDB Client:

Python

### Full Name:

Jamal Saepul Aziz

### Affiliation:

None

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@jamalsa thanks for reporting this. I managed to reproduce it, we'll take a look.

**Comment by pdet** [comment]
@jamalsa Thanks for the report! This is indeed an issue with the new sniffer.
This file has a lot of new lines in between actual data, and these were not being properly managed, which also forced our sniffer to read much more data than necessary to detect types and dialect.
I just worked on a fix, will wait for CI before PR-ing it.

**Comment by pdet** [comment]
@jamalsa, the fix was merged. Could you give it a go with master and check if it solved your issue? Otherwise, please re-open this!

**Comment by jamalsa** [comment]
Unfortunately the issue is still there. I installed master using this instruction: https://duckdb.org/docs/guides/python/install.html.

I reduced the to 1000 lines (500 csv records) and the error still the same. Then I reduced to just 100 lines (50 csv record) and got different error: `duckdb.duckdb.InternalException: INTERNAL Error: 'back' called on an empty vector!`.

I attached the two files here.
[male_1000.csv](https://github.com/duckdb/duckdb/files/12755430/male_1000.csv)
[male_100.csv](https://github.com/duckdb/duckdb/files/12755437/male_100.csv)

**Comment by Mause** [comment]
> Unfortunately the issue is still there. I installed master using this instruction: https://duckdb.org/docs/guides/python/install.html.
> 
> I reduced the to 1000 lines (500 csv records) and the error still the same. Then I reduced to just 100 lines (50 csv record) and got different error: `duckdb.duckdb.InternalException: INTERNAL Error: 'back' called on an empty vector!`.
> 
> I attached the two files here. [male_1000.csv](https://github.com/duckdb/duckdb/files/12755430/male_1000.csv) [male_100.csv](https://github.com/duckdb/duckdb/files/12755437/male_100.csv)

That sounds like https://github.com/duckdb/duckdb/issues/9111 - can you confirm with which version and git hash you tried?

**Comment by jamalsa** [comment]
@Mause I am using commit https://github.com/duckdb/duckdb/commit/2d59ecbd2808a316e1d7d70fe1ee4cdb07761f65 and version 0.9.1.dev36+g2d59ecbd28

**Comment by jamalsa** [comment]
I managed to pin down the problem. Here is the minimal troublesome data:
```csv
player_id,player_url,fifa_version,fifa_update,fifa_update_date,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,dob,height_cm,weight_kg,league_id,league_name,league_level,club_team_id,club_name,club_position,club_jersey_number,club_loaned_from,club_joined_date,club_contract_valid_until_year,nationality_id,nationality_name,nation_team_id,nation_position,nation_jersey_number,preferred_foot,weak_foot,skill_moves,international_reputation,work_rate,body_type,real_face,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,ls,st,rs,lw,lf,cf,rf,rw,lam,cam,ram,lm,lcm,cm,rcm,rm,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb,gk,player_face_url

165153,/player/165153/karim-benzema/230009,23,9,2023-01-13,K. Benzema,Karim Benzema,"CF, ST",91,91,64000000,450000,34,1987-12-19,185,81,53,La Liga,1,243,Real Madrid,CF,9,,2009-07-09,2023,18,France,,,,Right,4,4,4,Medium/Medium,Normal (170-185),Yes,131200000,"#Poacher, #Clinical Finisher","Leadership, Finesse Shot, Playmaker (AI), Outside Foot Shot, Team Player",80,88,83,87,39,78,75,92,90,89,88,87,82,73,76,91,79,80,78,92,72,87,79,82,82,80,63,39,92,89,84,90,43,24,18,13,11,5,5,7,,89+2,89+2,89+2,87,89,89,89,87,88+3,88+3,88+3,86+3,81+3,81+3,81+3,86+3,64+3,64+3,64+3,64+3,64+3,60+3,55+3,55+3,55+3,60+3,18+3,https://cdn.sofifa.net/players/165/153/23_120.png


```

This data will raise error `Invalid Input Error: CSV options could not be auto-detected. Consider setting parser options manually`.
If I remove the blank line between header and first data row, DuckDB can parse the file.

Another interesting problem is if I leave the blank line after header and remove one of blank line in the end it will raise error `duckdb.duckdb.InternalException: INTERNAL Error: 'back' called on an empty vector!`.

I applied this fix (remove blank line between header and first data) to csv with 1000 and now duckdb can parse the csv.

Here are parse time for each tests:
- 1000 lines: 0.07960915565490723s
- 10000 lines: 6.529728174209595s
- 100000 lines: 70.7232301235199s

So the parse time is increased with more lines whereas in v0.8.1 it is very quick (0.6689996719360352s).

The disappointing thing is when I remove the first blank line from the original file it still return the same error. So I think there is another problem there 😞.

**Comment by pdet** [comment]
Hi @jamalsa, I haven't been able to reproduce these issues on my machine with the two files you provided. I've tried both Mac OS and a Windows machine (to check it was not some carriage return issue). I've also tried the Python client on both OSs. You can also install the Python client nightly build with `pip install duckdb --pre`, so instead of building the sources, maybe you can try this?

I do understand that unexpected issues can cause some frustration, and I do appreciate you reporting a valid reproducible issue.

However, I would also like to point out that efficient CSV parsing is quite a complex feature. CSV files are very unruly and can come in very different shapes and forms. Coverage of all these differences can be very daunting. We make a best effort by having many different files that are tested in our CI using various configurations. Nevertheless, problems can slip through, especially now that we are drastically changing our CSV parsing algorithm, to avoid some of the main performance bottlenecks (See #8253 as an example).

In any case, if the error persists could you share more information on your Machine HW.

**Comment by jamalsa** [comment]
@pdet I just tried again with latest nightly (0.9.1.dev67) and it works now with read time 0.8489835262298584s.
@wa008 you should try it with latest nightly.

Thanks @pdet @szarnyasg @Mause for your support. Really appreciate it.
