### ISSUE TITLE
R function duckdb_read_csv() uses excessive memory?

### ISSUE THREAD

**Issue by cboettig** [duckdb/duckdb#988]
I am attempting to use the bulk importer to read in a large table from `tsv`.  I was surprised to see my machine quickly runs out of available memory (~ 60 GB), as if I was trying to import the file into memory instead of reading into the on-disk database.  This may be related to checkpointing (#420, #926, #973)?  

Here's an example using the ebird dataset, which is 101 GB (compressed). 

```r
## ~ 101 GB
ebird_url <- "https://minio.thelio.carlboettiger.info/shared-data/ebird/ebd_relAug-2020.txt.gz"
ebird <- "ebd_relAug-2020.txt.gz"
download.file(ebird_url, ebird)

con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "local_database")
duckdb_read_csv(con, 
                "ebird", 
                ebird, 
                delim = "\t",
                nrow.check=2e4)
```

**Comment by hannesmuehleisen** [comment]
Downloading now, will have a look if there is a workaround for this.

**Comment by cboettig** [comment]
Did the above example work on your end?  

Just a note that I'm still seeing memory issues with the bulk importer example shown above.  Using `duckdb` GitHub version, I no longer have any problem reading in large tables when streaming them through R and writing out via the DBI interface (`dbWriteTable()`), but the above code still consistently runs me out of RAM and crashes the session.

**Comment by mskyttner** [comment]
@cboettig I'm interested in your approach when streaming through R - do you read chunks from the source and write those chunks to a duckdb target connection and for every chunk you close the duckdb connection and open it again? 

I have a similar issue with a not as big table as you seem to be using (around 170 M rows), and I'm trying this approach currently to sync this data from MySQL into duckdb:

```r
  rc_sql <- sprintf("SELECT COUNT(*) as n FROM %s;", table)
  rc <- dbGetQuery(con_src, rc_sql) %>% purrr::as_vector()
  p <- progress_estimated(n = ceiling(rc / chunk_size))

  rs_sql <- sprintf("SELECT * FROM %s;", table)
  rs <- dbSendQuery(con_src, rs_sql)

  iter <- 0
  if (overwrite) DBI::dbRemoveTable(con_dest, table)
  while (!dbHasCompleted(rs)) {
    iter <- iter + 1
    chunk <- DBI::dbFetch(rs, chunk_size) %>% as_tibble()
    # it seems the connection can auto-disconnect, for example if connected > 1h to RMySQL con
    if (!DBI::dbIsValid(con_src)) con_src <- db_reconnect(con_src)
    if (!DBI::dbIsValid(con_dest)) con_dest <- db_reconnect(con_dest)
    DBI::dbWriteTable(con_dest, table, chunk, append = TRUE)
    p$pause(0.1)$tick()$print()
    if (iter %% 1e2 == 0) message("Rows fetched: ", iter * chunk_size)
  }
  DBI::dbClearResult(rs)
```
Any hints or suggestions about the best way to stream/chunk data into duckdb using the R package?

**Comment by cboettig** [comment]
@mskyttner of course the bulk importer mentioned above _should_ be the best way, and can likely be a lot faster than streaming chunks, but as noted above I'm still having issues with RAM on that, even with the most recent `duckdb` release.  Looks like you're exporting from a MySQL db though?  Have you tried going via a [csv flatfile](https://mariadb.com/kb/en/select-into-outfile/) rather than directly db -> R -> db?

For chunking, I'm using the R package `arkdb`, https://github.com/ropensci/arkdb, though the process is essentially the same as the iteration you outline.

**Comment by mskyttner** [comment]
@cboettig thanks for those suggestions, I'm using MySQL/MariaDB and SQLite3 for the source data when moving it to duckdb. I'll try the duckdb CLI command, importing from a flatfile, bypassing R, and then compare it to the `duckdb_read_csv()` function.

**Comment by cboettig** [comment]
@Mytherin @hannesmuehleisen Is this working on your end?  In general memory management has felt a lot more snappy in the recent releases, but `duckdb_read_csv()` on large files like the above I'm still seeing the same behavior where duckdb consumes all the available memory and then crashes the R session.

**Comment by Mytherin** [comment]
I have just tested it by setting `pragma memory_limit='4GB';` and loading a CSV file of 40GB, and in general the memory usage did not go much higher than 4GB (it went up to about`4.75G` in total; which is expected since the memory limit currently only applies to "large chunks" of the data and certain intermediates are not counted).

In general the workflow of loading a larger-than-memory CSV into the system is not optimized though, since it will:

* Load the CSV into memory, which will swap if it doesn't fit within the memory limit (by writing the in-memory DuckDB format to the `database.db.tmp` directory)
* Read from that again and write it to the WAL (`database.db.wal`)
* Read from that again and write it to the database on checkpoint

This means there are 3 round trips to disk on bigger-than-memory CSVs, and the data will also be on disk multiple times. We for sure need to optimize this path still. However, it does seem to correctly support the memory limit if specified.

* Could you verify that the memory limit is correctly set (using `pragma database_size;`)?
* If it is, could you verify that you have enough space to have the database on disk ~3 extra times? It could be that the crash you are seeing is related to the system running out of disk space rather than running out of memory.

**Comment by cboettig** [comment]
Thanks @Mytherin  -- no, I'm not setting `pragma memory_limit` at all, didn't know about that. So yeah, I watch it hit the 200 GB RAM cap on my container and the OOM kills it.  

 How does one actually setting the pramga_memory_limit? (It's not set before compiling is it?  I'm using `duckdb` as the backend for certain user-facing R packages, so the users will be installing duckdb prebuilt binaries from CRAN, and I thus I need an option via the R API ... I didn't see any such option in `duckdb::duckdb()` establishing the connection...

Even with the pragma limit, swapping sounds like it's going to make things really slow.  And of course I don't have control over whether or not a user happens to have swap enabled.

3x disk space isn't ideal but of these issues, that one concerns me the least. I feel fine assuming most users today have substantially more disk space than RAM.  I'm just really looking for a good on-disk paradigm to work with data that is too big for RAM, and really hoping `duckdb` is the ticket!

**Comment by Mytherin** [comment]
> Thanks @Mytherin -- no, I'm not setting pragma memory_limit at all, didn't know about that. So yeah, I watch it hit the 200 GB RAM cap on my container and the OOM kills it.

It's not set during compilation; this is a SQL query that you run, i.e. where-ever you input SQL you can run:

```sql
PRAGMA memory_limit='10GB';
```

And it will limit the memory usage of the system.

I assume somewhere you are running SQL queries :)

> Even with the pragma limit, swapping sounds like it's going to make things really slow. And of course I don't have control over whether or not a user happens to have swap enabled.

In general the swapping should only occur during loading, and only when loading a single CSV that exceeds RAM. This should also be resolved in the future, it is only a current limitation of the data insertion pipeline in which we don't directly write to the database file, but instead first write to the in-memory storage, and then write to the WAL.

This is not a big problem if the data fits in memory, but becomes a problem when the temporary in-memory storage needs to be written to disk (on account of inserting a lot of data within a single transaction, as happens if reading e.g. a single huge CSV file).

> 3x disk space isn't ideal but of these issues, that one concerns me the least. I feel fine assuming most users today have substantially more disk space than RAM. I'm just really looking for a good on-disk paradigm to work with data that is too big for RAM, and really hoping duckdb is the ticket!

In general this is one of our design goals, so I hope we can provide this for you! Any reported issues help us improve in this regard as well so they are more than welcome :)

**Comment by cboettig** [comment]
ah, thanks for the clarification!

Would it be possible to add `memory_limit` as an argument to `duckdb_read_csv` then?  (No I'm not actually writing SQL here, I'm just calling duckdb_read_csv() as in the example at top; hopefully said example is fully copy-paste reproducible :-) )

Most of my package users aren't writing their own SQL either, they rely on `dplyr` to do the SQL translation.  I can probably hack a helper function that would amend this to the SQL call that's produced if necessary, though so far I don't really encounter the issues of RAM limits once the data is imported.  

And yup, I totally understand a lot of these issues don't arise when data fits into RAM, it's just the cases where data doesn't fit into RAM are my reason for going to duckdb.  The swap issue doesn't sound like a deal-breaker though, particularly if it gets fixed down the line.

**Comment by cboettig** [comment]
(just for the record, I have also tried:

```r
con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "ebird_database")
DBI::dbExecute(con, "PRAGMA memory_limit='10GB'")
DBI::dbExecute(con, "SELECT * FROM read_csv_auto('import_dir/ebd_relAug-2020.txt');")
```
(where the .txt file is the one mentioned above), but also see the system consume the avialable 200 GB ram on the container and then crash the session.  Same behaviour if I switch the data over to parquet format and run with

```

DBI::dbExecute(con, "SELECT * FROM parquet_scan('ebird_parquet/part-0.parquet');")

```

**Comment by cboettig** [comment]
@Mytherin Hi Mark, sorry to bug you, just wondered if you could let me know if I'm simply doing the `PRAGMA` declaration incorrectly above?  It definitely continues to consume all available RAM

**Comment by Mytherin** [comment]
> (just for the record, I have also tried:
> 
> ```r
> con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "ebird_database")
> DBI::dbExecute(con, "PRAGMA memory_limit='10GB'")
> DBI::dbExecute(con, "SELECT * FROM read_csv_auto('import_dir/ebd_relAug-2020.txt');")
> ```
> 
> (where the .txt file is the one mentioned above), but also see the system consume the avialable 200 GB ram on the container and then crash the session. Same behaviour if I switch the data over to parquet format and run with
> 
> ```
> 
> DBI::dbExecute(con, "SELECT * FROM parquet_scan('ebird_parquet/part-0.parquet');")
> ```

The pragma seems fine to me. Do you intend to do a `SELECT *` here? That loads the entire result set into memory and subsequently your R shell, and indeed that part is not buffer managed right now, but this is down to the R connector not to the main database engine.

Perhaps the R connector could hand back the result set to R as a memory mapped file to alleviate that problem, but I'm not sure if this is what you intend to do.

I started downloading your file some days ago and it has not finished, but doing some preliminary experiments loading the first part of the file into a physical database seems to correctly cap the memory. Looking at `htop` here the system never seems to exceed much more than 10GB of memory (peak is ~10.5GB), while the database grows to 63GB. So at least when doing a create table statement, and several simple queries, the memory limit seems to work as expected on your dataset as well:

```sql
pragma memory_limit='10gb';
create table t1 as select * from read_csv_auto('ebd_relAug-2020.txt.gz') limit 100000000;
D pragma database_size;
┌───────────────┬────────────┬──────────────┬─────────────┬─────────────┬──────────┬──────────────┬──────────────┐
│ database_size │ block_size │ total_blocks │ used_blocks │ free_blocks │ wal_size │ memory_usage │ memory_limit │
├───────────────┼────────────┼──────────────┼─────────────┼─────────────┼──────────┼──────────────┼──────────────┤
│ 63.0GB        │ 262144     │ 240700       │ 240700      │ 0           │ 0 bytes  │ 0 bytes      │ 10.0GB       │
└───────────────┴────────────┴──────────────┴─────────────┴─────────────┴──────────┴──────────────┴──────────────┘

```

**Comment by cboettig** [comment]
@Mytherin thanks!  Apologies about my limited SQL, I'm working only within the context of the R client.  I took the `SELECT` command from the duckdb documentation:, https://duckdb.org/docs/data/csv and https://duckdb.org/docs/data/parquet.  It sounds like the memory issues I'm seeing are related to how I'm using the R client to communicate with duckdb.  Can you provide any instructions that can be run in R alone that will allow me to import the data with a memory limit set?  Ideally I'd like to just use your R function, `duckdb_read_csv()`, as up top, perhaps with some optional argument?

> Perhaps the R connector could hand back the result set to R as a memory mapped file to alleviate that problem, but I'm not sure if this is what you intend to do.

I'm afraid this went over my head.  Apologies if I haven't stated my goal here well.  All I want to do is import a csv file into duckdb using `duckdb_read_csv()` (or alternative R code) with a file that is larger than available RAM.  Does this mean that it is not possible with the way the DBI package or the duckdb R client currently works? 

Thanks again!

**Comment by Mytherin** [comment]
Perhaps @hannesmuehleisen would be better suited at explaining the R interface, but I think the `duckdb_read_csv` does what you want to do: it loads a CSV file into a DuckDB table that is persisted on disk. The DuckDB table can then be manipulated using SQL queries, or read (partly) into R. As long as the data resides in DuckDB the memory limit should work fine, and you can use e.g. dbplyr to work with the data.

When reading the data into R directly (using e.g. `dbReadTable`), the data is read entirely from the file on disk and converted into an R data frame. As far as I'm aware it uses the regular R API for that, which generates these entirely in memory. It might be possible to convert these into memory mapped files instead which could overflow to disk, but I'm not sure how desirable that even is as R is itself not optimized to handle out-of-memory data.

**Comment by cboettig** [comment]
Thanks @Mytherin , really appreciate you taking the time to work through this with me.  

Maybe a more concise way to put this is that I want `duckdb_read_csv()` to work like the now deprecated `MonetDBLite::monet.read.csv`.  This function has no problem reading in a file much better than RAM into the local database.

>  As long as the data resides in DuckDB the memory limit should work fine, and you can use e.g. dbplyr to work with the data.

I thought `duckdb_read_csv` should be able to trigger the duckdb database to import data that does not fit in the memory limit as well, like `monet.read.csv`.  Does this mean that is wrong?

> When reading the data into R directly (using e.g. dbReadTable), the data is read entirely from the file on disk and converted into an R data frame. As far as I'm aware it uses the regular R API for that, which generates these entirely in memory. 

Yes, `DBI::dbReadTable` will read a full table into R's memory, which is clearly not a scalable strategy, but I don't think that's relevant here.  Your `duckdb_read_csv` function does not call `dbReadTable`,  nor does the monet function. Those functions send commands through more low-level interfaces. Likewise the whole purpose of the `dbplyr` interface is to avoid the need for dbReadTable, by sending SQL commands to the database which allow the heavy lifting to run outside of R on the database.  R doesn't have to handle out-of-memory data, dbplyr merely does a bit of meta-programming to allow the SQL database backend to handle all the SQL observations (sorry you probably know this already, I was merely confused by your comments).  

MonetDBLite was a game changer for us in the R community, because suddenly we could use the dbplyr backend to handle all these cases of data that was much larger than available RAM without spinning up a stand-alone Postgres server or relying or compromising on performance (and other operations) by falling back to SQLite.  While I appreciate that duckdb can outperform dplyr on in-memory datasets, performance on in-memory datasets isn't really that limiting.  It's only the datasets too big for RAM that made MonetDBLite such a transformation.  I'm excited for `duckdb` to take it's place, but the memory use of `duckdb_read_csv` keeps us relying on `monet.read.csv()` (which we can no longer use by default since it is not on CRAN) or SQLite for the time being

**Comment by Mytherin** [comment]
> I thought duckdb_read_csv should be able to trigger the duckdb database to import data that does not fit in the memory limit as well, like monet.read.csv. Does this mean that is wrong?

This should work fine.

> Yes, DBI::dbReadTable will read a full table into R's memory, which is clearly not a scalable strategy, but I don't think that's relevant here. Your duckdb_read_csv function does not call dbReadTable, nor does the monet function. Those functions send commands through more low-level interfaces. Likewise the whole purpose of the dbplyr interface is to avoid the need for dbReadTable, by sending SQL commands to the database which allow the heavy lifting to run outside of R on the database. R doesn't have to handle out-of-memory data, dbplyr merely does a bit of meta-programming to allow the SQL database backend to handle all the SQL observations (sorry you probably know this already, I was merely confused by your comments).

I completely agree, and all of that should work. The thing is that in your above code sample you (basically) call `dbReadTable` to load everything into R:

> DBI::dbExecute(con, "SELECT * FROM read_csv_auto('import_dir/ebd_relAug-2020.txt');")

`dbReadTable(table)` is (more or less) equivalent to `dbExecute("SELECT * FROM table")`, hence here you are loading the entire file into R much like you would using `dbReadTable`. Indeed this is not scalable, hence my confusion.

Have you tried setting `PRAGMA memory limit`, followed by `duckdb_read_csv`, and checking if that still gives you the same memory problems?

**Comment by cboettig** [comment]
Now why didn't I try that?!  

I'm running: 

```r
con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "duckdb_database")
DBI::dbExecute(con, "PRAGMA memory_limit='10GB'")
duckdb::duckdb_read_csv(con, name = "ebird", files = "import_dir/ebd_relAug-2020.txt", delim = "\t", nrow.check=1e5)
```

now. 23 minutes in, seems to be holding steady at 10.5 G memory use, with about ~90-100 MB/s read rate.  Periodically i see the write rate burst up to ~ 1 GB/s and then go back to 0, suggesting that it is indeed writing to disk, and `duckdb_database.tmp` file is at 251G, though `duckdb_database` and `duckdb_database.wal` are still 12K and 4K. So looks like it's all working nicely!  Apologies again for my confusion.

 Will I still need to cycle the connection open/close to finish the import?

**Comment by Mytherin** [comment]
> now. 23 minutes in, seems to be holding steady at 10.5 G memory use, with about ~90-100 MB/s read rate. Periodically i see the write rate burst up to ~ 1 GB/s and then go back to 0, suggesting that it is indeed writing to disk, and duckdb_database.tmp file is at 251G, though duckdb_database and duckdb_database.wal are still 12K and 4K. So looks like it's all working nicely! Apologies again for my confusion.

No worries, glad it's working now! The `.tmp` directory should be filled first, after which the `.wal` is filled, and after that the `.db` is filled. In the next release we hope to go straight from `.tmp` to `.db` (saving one full write to disk). Writing straight to the database file is also possible, but more challenging particularly in the presence of multiple connections/transactions. We are thinking about adding a "single connection" flag to the system, which would allow the file to be written straight to the database file, at the expense of not allowing multiple clients to connect to the database.

> Will I still need to cycle the connection open/close to finish the import?

On the latest release I believe this is still necessary. On the master we now support checkpointing during runtime and incremental checkpointing, so you can manually call `CHECKPOINT` or shut down the database and everything should be written to the database file.

**Comment by mskyttner** [comment]
I tried bulk loading of a 100+ million row table using duckdb 0.2.4, so not a huge dataset but might still be interesting as there were some RAM and disk full issues in the process. Here is a write-up with some notes comparing two approaches - doing it using R and using the duckdb CLI:

### chunkwise through R

The data I worked with came from a flatfile of 5.3 Gb (csv/tsv format) with 130 million rows of data, an extract generated from a [SQLite db available here](https://archive.org/download/aquamapsdb/am.db.bz2) with arkdb in tsv.bz2 compressed format. I tried loading it in a chunkwise fashion from R, using vroom for reading chunks of 5 million rows per chunk. 

When writing chunks to duckdb I tried to use duckdb_register with the data chunk read from vroom, followed by "insert into my_table select * from chunk". In the first attempt I ran out of disk space. As a result, the database file appeared to become corrupted and I could not open it anymore. I tried to open it from R and from duckdb CLI/shell after cleaning up some disk space. The error I got was: 
  
```r
Error in duckdb_execute(res) : duckdb_execute_R: Failed to run query
Error: TransactionContext Error: Failed to commit: IO Error: Could not write file "/home/markus/repos/aquamapsdata/duckdb_database.wal": No space left on device
```

I then tried again, now with about 25 Gb disk free and now using a separate connection when writing each chunk with the hope to flush the write ahead log WAL incrementally. This approach worked out, and the total time spent reading the data (using vroom) was 112 seconds for approx 27 chunks, each with 5 million rows of data. The total time spent writing to duckdb was 511 seconds. Grand total was about 10 minutes.

Initially reading from vroom and writing to duckdb (for the first chunk) felt fast. Subsequent chunks were still fast to read via vroom, with 1.8 million rows per second but decreasing for later chunks; when the last chunk was done it was down to 1.2 million rows per second, probably due to later chunks requiring an increasingly longer scan up to the "starting line" for the chunk being read.

For writing subsequent chunks beyond the first one to duckdb, there was a more significant decrease in speed, probably mostly because of my "poor mans" checkpointing since I'm not yet using the latest master version of duckdb that has "checkpoint;"-funtionality. I tried to achieve forced flushing of the WAL by opening and shutting down a connection to duckdb for each chunk being processed. Maybe the gradual slower write speeds for chunks also has to do with something else happening after appending chunks? What is causing this? Rebuilding of indexes? Transactions get logged/stored in a journal?

The resulting duckdb database file ended up at about 19 Gb on disk (twice the equivalent SQLite file which also includes some indexes, but not on all columns).

R functions/scripts used are at the gist below:

```r
library(duckdb)

source("https://gist.githubusercontent.com/mskyttner/5140bcd074b844263de5c3a2bef4bded/raw/71c8adf1f8af226fb8e0b967a23b898ff0c4c126/duck_copy_csv.R")

chunk_stats <-
  duck_copy_csv(
    csvfile = "data-raw/ark/hcaf_species_native.tsv",
    dbfile = "duckdb_database",
    tablename = "hcaf_species_native", overwrite = T,
    checkpoint = TRUE, csv_chunksize = 5e6
  )
```
Results: 

![duck_csv_01](https://user-images.githubusercontent.com/1715840/107887396-223f6900-6f06-11eb-8bdd-25042b65be36.png)

| chunk|       beg|       end|is_done |    nrow|t_read        |t_write        |mem_chunk |mem_used |free_disk |
|-----:|---------:|---------:|:-------|-------:|:-------------|:--------------|:---------|:--------|:---------|
|     1|         1|   5000001|FALSE   | 5000000|2.899175 secs |2.475212 secs  |276.4 Mb  |173.4 Mb |22G       |
|     2|   5000001|  10000001|FALSE   | 5000000|2.607298 secs |4.079245 secs  |277 Mb    |175 Mb   |22G       |
|     3|  10000001|  15000001|FALSE   | 5000000|2.844277 secs |5.313453 secs  |277 Mb    |175.1 Mb |21G       |
|     4|  15000001|  20000001|FALSE   | 5000000|2.906520 secs |6.105941 secs  |276.7 Mb  |175.1 Mb |21G       |
|     5|  20000001|  25000001|FALSE   | 5000000|3.079535 secs |7.400713 secs  |277.3 Mb  |175.1 Mb |20G       |
|     6|  25000001|  30000001|FALSE   | 5000000|3.183478 secs |8.071847 secs  |277.3 Mb  |175.1 Mb |19G       |
|     7|  30000001|  35000001|FALSE   | 5000000|3.207165 secs |9.128015 secs  |276.1 Mb  |175.1 Mb |18G       |
|     8|  35000001|  40000001|FALSE   | 5000000|3.452358 secs |9.821118 secs  |277.2 Mb  |175.1 Mb |18G       |
|     9|  40000001|  45000001|FALSE   | 5000000|3.650162 secs |10.597709 secs |276.9 Mb  |175.1 Mb |17G       |
|    10|  45000001|  50000001|FALSE   | 5000000|3.453447 secs |10.851804 secs |276.2 Mb  |175.1 Mb |16G       |
|    11|  50000001|  55000001|FALSE   | 5000000|3.768770 secs |11.825384 secs |276.5 Mb  |175.1 Mb |15G       |
|    12|  55000001|  60000001|FALSE   | 5000000|3.714545 secs |12.310129 secs |275.3 Mb  |175.1 Mb |15G       |
|    13|  60000001|  65000001|FALSE   | 5000000|4.102273 secs |14.118358 secs |277 Mb    |175.1 Mb |14G       |
|    14|  65000001|  70000001|FALSE   | 5000000|4.035439 secs |16.331255 secs |275.7 Mb  |175.1 Mb |13G       |
|    15|  70000001|  75000001|FALSE   | 5000000|4.383209 secs |18.753674 secs |275.3 Mb  |175.1 Mb |13G       |
|    16|  75000001|  80000001|FALSE   | 5000000|4.287312 secs |19.402784 secs |275.1 Mb  |175.1 Mb |12G       |
|    17|  80000001|  85000001|FALSE   | 5000000|4.628474 secs |21.073651 secs |276.3 Mb  |175.1 Mb |11G       |
|    18|  85000001|  90000001|FALSE   | 5000000|4.546188 secs |21.269837 secs |277.1 Mb  |175.1 Mb |9,9G      |
|    19|  90000001|  95000001|FALSE   | 5000000|4.709217 secs |23.970053 secs |276.2 Mb  |175.1 Mb |9,2G      |
|    20|  95000001| 100000001|FALSE   | 5000000|4.725898 secs |28.952140 secs |275.5 Mb  |175.1 Mb |8,5G      |
|    21| 100000001| 105000001|FALSE   | 5000000|5.118637 secs |32.564002 secs |275.8 Mb  |175.1 Mb |7,8G      |
|    22| 105000001| 110000001|FALSE   | 5000000|5.519130 secs |38.720005 secs |277.5 Mb  |175.1 Mb |7,0G      |
|    23| 110000001| 115000001|FALSE   | 5000000|5.639491 secs |41.694178 secs |277.5 Mb  |175.1 Mb |6,3G      |
|    24| 115000001| 120000001|FALSE   | 5000000|5.709834 secs |41.436651 secs |277.9 Mb  |175.1 Mb |5,6G      |
|    25| 120000001| 125000001|FALSE   | 5000000|6.336750 secs |47.231693 secs |277.1 Mb  |175.1 Mb |4,9G      |
|    26| 125000001| 130000001|FALSE   | 5000000|5.753192 secs |46.813185 secs |276.7 Mb  |175.1 Mb |4,1G      |
|    27| 130000001| 135000001|TRUE    |  176393|4.368002 secs |1.235121 secs  |11.3 Mb   |175.1 Mb |3,4G      |

## bulk loading with duckdb CLI

I then attempted to bypass R to do the same bulk load, but not a chunkwise approach and instead using the duckdb CLI-tool and doing two transactions (one to load the schema for the table and one to fill it with data). 

I first tried using .import and .sep '\t', as per the documentation, but got an error saying multi-character column separators not allowed for import (I used tab separated values, but it seems my \t character counted as two characters). 

Instead of converting the .tsv.bz2 to .csv I tried using two statements, first "CREATE TABLE tablename AS SELECT * FROM read_csv_auto('head.tsv', HEADER=TRUE);" with head.tsv being 1000 initial rows of data. Then I dropped the data and reloaded with "INSERT INTO tablename SELECT * FROM read_csv_auto('data.tsv', HEADER=FALSE);" where data.tsv was the data I wanted to bulk load. Finally I started and stopped the database, since that seemed to flush the WAL-file with the duckdb version I used (after running a select count(*) first).

The resulting duckdb database ended up at about 9 Gb on disk, more similar to the size of the SQLite file with the same data.

This non-chunked load took 5 minutes to complete, half of the time compared to when I used R.

I used [this bash script](https://gist.github.com/mskyttner/718dcda15c3d62895e0e808ec2ec3aca) to load via the duckdb CLI.

# Thoughts

Writing a stream of data to duckb using a "buffered stream bulk loader" taking data from stdin (which gets buffered/chunked as required) straight into a duckdb table would be a nice feature. Maybe something to allow "CREATE TABLE test AS SELECT * FROM read_csv_auto('/dev/stdin');" or equivalent, to support usage like:

```bash
bunzip2 -d -c mytsvfile.tsv.bz2 | pv | duckdb duckdb_database "COPY mybulkloadtable FROM read_csv_auto('/dev/stdin');"
```
 
I could not get reading from '/dev/stdin' to work in the duckdb CLI, when piping a tsv to it; reading seemed to start but I got an input error when I made the following attempt:
  
    CREATE TABLE testy AS SELECT * FROM read_csv_auto('/dev/stdin', HEADER=TRUE, SEP='\n', DELIM='\t', SAMPLE_SIZE=-1);
    # Error: near line 1: Invalid Input Error: Maximum line size of 1048576 bytes exceeded!
    # Error: near line 1: Parser Error: syntax error at or near "RecordID"
    # LINE 1: RecordID	CsquareCode	SpeciesID	SpecCode	Goo...


It would be nice to set options to tune writing, maybe stuff like "PRAGMA journal_mode=off;" and other ways to set number of threads (all but one by default), mem limits, chunking/buffering/periodic commits etc. That would be nice when bulk loading from a stream and writing into a duckdb table. Or if such stream bulk loading cannot or should not be embedded in duckdb, it would be nice to be able to do it from outside on the CLI using something similar to https://github.com/cvilsmeier/sqinn to have something to take care of buffering/chunking a stream input, but it would be faster if it can happen in-process, I guess.

**Comment by Mytherin** [comment]
> I tried bulk loading of a 100+ million row table using duckdb 0.2.4, so not a huge dataset but might still be interesting as there were some RAM and disk full issues in the process. Here is a write-up with some notes comparing two approaches - doing it using R and using the duckdb CLI:

Thanks for your detailed report, this is very helpful!

> For writing subsequent chunks beyond the first one to duckdb, there was a more significant decrease in speed, probably mostly because of my "poor mans" checkpointing since I'm not yet using the latest master version of duckdb that has "checkpoint;"-funtionality. I tried to achieve forced flushing of the WAL by opening and shutting down a connection to duckdb for each chunk being processed. Maybe the gradual slower write speeds for chunks also has to do with something else happening after appending chunks? What is causing this? Rebuilding of indexes? Transactions get logged/stored in a journal?

The current release of DuckDB rewrites the entire database on checkpoint, which explains why it gets gradually slower (bigger database = more data to rewrite). This should be fixed in the master now.

> I first tried using .import and .sep '\t', as per the documentation, but got an error saying multi-character column separators not allowed for import (I used tab separated values, but it seems my \t character counted as two characters).

> Instead of converting the .tsv.bz2 to .csv I tried using two statements, first "CREATE TABLE tablename AS SELECT * FROM read_csv_auto('head.tsv', HEADER=TRUE);" with head.tsv being 1000 initial rows of data. Then I dropped the data and reloaded with "INSERT INTO tablename SELECT * FROM read_csv_auto('data.tsv', HEADER=FALSE);" where data.tsv was the data I wanted to bulk load. Finally I started and stopped the database, since that seemed to flush the WAL-file with the duckdb version I used (after running a select count(*) first).

So `.import` uses the SQLite shell's CSV reader, which is rather primitive. Using the `read_csv_auto` uses DuckDB's CSV reader which is both more capable and much faster. It's worth noting that you can use this from any language, not just from the shell (i.e. you can just write the same query using dbExecute as well, no shell required).

> It would be nice to set options to tune writing, maybe stuff like "PRAGMA journal_mode=off;" and other ways to set number of threads (all but one by default), mem limits, chunking/buffering/periodic commits etc. That would be nice when bulk loading from a stream and writing into a duckdb table.

We have thought of that, and indeed think this would be a good addition. Thanks for the feedback!

**Comment by cboettig** [comment]
Thanks again for  the help here @Mytherin and @hannesmuehleisen !  In my case above in https://github.com/cwida/duckdb/issues/988#issuecomment-778520144, I'm still getting killed on OOM error when trying to re-establish the connection "after" doing the import, 

```r
con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "duckdb_database")
```

As Hans noted I gather this is doing the required power-cycle to trigger the import from the tmp / wal files, but unfortunately, since I don't have the connection established before running this, I have no way of setting the PRAGMA memory limit now.  As a result this keeps crashing.  (Again no troubles doing this on the MonetDBLite version)

**Comment by Mytherin** [comment]
Are you running on the master or the latest release? This should be fixed in the master branch already.

**Comment by cboettig** [comment]
Tested on master branch yesterday, this morning it looks like it ran out of RAM on the import step?

```
> library(duckdb)
> ebd <- "ebd_relAug-2020.txt"
> con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "ebird_database")
> DBI::dbExecute(con, "PRAGMA memory_limit='10GB'")
[1] NA
> duckdb::duckdb_read_csv(con, name = "ebird", files = ebd, delim = "\t", nrow.check=1e5)
Error in duckdb_execute(res) : duckdb_execute_R: Failed to run query
Error: Out of Range Error: Not enough memory to complete operation: could not allocate block of 262144 bytes
```

**Comment by cboettig** [comment]
@Mytherin Just a heads up that I'm getting memory errors on the latest master branch as noted above.  On the CRAN version `duckdb_read_csv` is fine, things only crash after restarting the connection,  But on the `master` version `ducdkb_read_csv` is once more throwing memory errors.  This time I get the `Out of Range Error` above instead of it being killed by the OOM.

**Comment by Mytherin** [comment]
Going to have another look at this then. Thanks for testing!

**Comment by Mytherin** [comment]
For me this now seems to work as intended, at least from the shell. Running the following three SQL queries correctly fills up the database and checkpoints it. It takes quite a while, and it does still write to disk twice (not three times anymore), but when it completes the file seems to be fully functional and checkpointed. 

The machine I was running on had 64GB RAM, but with the memory limit set not all of this was used. Memory during load peaked at around 11.8GB; slightly higher than 10GB but not significantly, this is expected.

```sql
D pragma memory_limit='10gb';
D create table ebd as select * from read_csv_auto('/export/scratch1/home/raasveld/ebd_relAug-2020.txt.gz');
D pragma database_size;
┌───────────────┬────────────┬──────────────┬─────────────┬─────────────┬──────────┬──────────────┬──────────────┐
│ database_size │ block_size │ total_blocks │ used_blocks │ free_blocks │ wal_size │ memory_usage │ memory_limit │
├───────────────┼────────────┼──────────────┼─────────────┼─────────────┼──────────┼──────────────┼──────────────┤
│ 500.3GB       │ 262144     │ 1908791      │ 1908791     │ 0           │ 0 bytes  │ 0 bytes      │ 10.0GB       │
└───────────────┴────────────┴──────────────┴─────────────┴─────────────┴──────────┴──────────────┴──────────────┘
```

Restarting is fast (~1 second), and querying works fine after that:

```sql
D select count(*) from ebd;
┌──────────────┐
│ count_star() │
├──────────────┤
│ 823755903    │
└──────────────┘
D select min(COUNTRY), max(country) FROM ebd;
┌──────────────┬──────────────┐
│ min(country) │ max(country) │
├──────────────┼──────────────┤
│ Afghanistan  │ Zimbabwe     │
└──────────────┴──────────────┘
```

I did fix an issue where the memory limit default was not correctly applied, it should now be set to 80% of available RAM automatically (see #1438).

I will give it a go from R next.

**Comment by cboettig** [comment]
@Mytherin Any luck with the R tests?  Installing from master, things no longer error out as before.  However, I'm seeing a simple filter query for a single element take about an hour in duckdb:

```
> con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "duckdb_database")
> DBI::dbExecute(con, "PRAGMA memory_limit='10GB'")
[1] NA
> bench::bench_time({
+   ebd <- dplyr::tbl(con, "ebird")
+   out <- dplyr::filter(ebd, `GLOBAL.UNIQUE.IDENTIFIER` == "URN:CornellLabOfOrnithology:EBIRD:OBS640439399") %>% collect()
+ })
process    real 
  51.6m   1.04h 
```

For comparison, using MonetDBLite, the same query from R about 3 minutes on the same machine (machine has an 8 TB PCIe Gen3 solid-state disk, 200 GB ram, 128 core).  

Regarding memory limits, I'm usually running in Docker containers on my server which have set the memory cap to something less than the total machine cap (e.g. maybe 70% of machine cap).  As a result, I think the mechanism that tries to stop OOM automatically by detecting available memory fails.  As you can see in the example above, to get things to work I need to manually set PRAGMA cap.  Again this is not an issue when using MonetDBLite in the same containerized setup.

**Comment by Mytherin** [comment]
Interesting, thanks for the report again!

> @Mytherin Any luck with the R tests? Installing from master, things no longer error out as before. However, I'm seeing a simple filter query for a single element take about an hour in duckdb:

I did try it in R and had similar results, no issues.

> For comparison, using MonetDBLite, the same query from R about 3 minutes on the same machine (machine has an 8 TB PCIe Gen3 solid-state disk, 200 GB ram, 128 core).

> Regarding memory limits, I'm usually running in Docker containers on my server which have set the memory cap to something less than the total machine cap (e.g. maybe 70% of machine cap). As a result, I think the mechanism that tries to stop OOM automatically by detecting available memory fails. As you can see in the example above, to get things to work I need to manually set PRAGMA cap. Again this is not an issue when using MonetDBLite in the same containerized setup.

So, MonetDBLite uses mmap to handle the out-of-memory situation. This has certain disadvantages (memory usage cannot be controlled, OS-dependent performance/behavior, read-ahead is limited to what the OS provides for you), but has a prime advantage in that the OS controls the memory management so the system (and, as a consequence, the user) does not need to worry about it.

I am thinking about adding a flag that allows DuckDB to use mmap as well. When this is done I will ping you and you can check if that resolves the issues you are having.

**Comment by cboettig** [comment]
@Mytherin Thanks Mark!  Regarding the query tests from R, did you try evaluating the `filter` test for ` `GLOBAL.UNIQUE.IDENTIFIER` == "URN:CornellLabOfOrnithology:EBIRD:OBS640439399"` ?  I can confirm that the simpler count and max queries you showed earlier are nice and fast ( << 1 second), e.g.

```
> bench::bench_time({  x = DBI::dbGetQuery(con, "select count(*) from ebird")  })
process    real 
  175ms   175ms 
> x
  count_star()
1    823755903
```

but extracting a single row matching that identifier takes over an hour, as shown above.  


Re mmap, thanks, that's really interesting!  I do think that would be handy to opt into for containerized setups.

**Comment by Mytherin** [comment]
Ah, that makes sense. The problem is that in the current design of the system any column that you include is fully scanned. That means that if you do a query in the form of `SELECT * FROM huge_table WHERE col1id=3`, the entire table is read from disk (and most of it is immediately thrown away again). This is generally not a big problem for in-memory workloads, but becomes very problematic when data has to be read from disk.

This should be solved when we implement lazy vectors (#396), which involves postponing reading the data from disk  until it is actually required (which, in the case of a very selective filter, is almost never).

**Comment by cboettig** [comment]
@Mytherin thanks Mark, that's very good to know!  I suspect that's probably responsible some related cases where we are also seeing much worse performance from `duckdb` (on disk) than from MonetDBLite (on disk).  I'll keep an eye on #396

duckdb is our go-to for big data needs where in-memory operations are not an option, so these  on-disk benchmarks of performance are crucial to us!

**Comment by hannesmuehleisen** [comment]
Just briefly chiming in here briefly from paternity leave, @cboettig, we are super thankful for you patience and help in tracking down these issues.

**Comment by hannesmuehleisen** [comment]
> things no longer error out as before.

I think this means we can close here. Feel free to reopen if this is not accurate.
